wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.9
    cli_version: 0.17.4
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1720475860
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.11.9
      5: 0.17.4
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
