wandb_version: 1

layer_1:
  desc: null
  value: 512
activation_1:
  desc: null
  value: relu
dropout:
  desc: null
  value: 0.3695269543814387
layer_2:
  desc: null
  value: 10
activation_2:
  desc: null
  value: softmax
optimizer:
  desc: null
  value: sgd
loss:
  desc: null
  value: sparse_categorical_crossentropy
metric:
  desc: null
  value: accuracy
epoch:
  desc: null
  value: 8
batch_size:
  desc: null
  value: 256
_wandb:
  desc: null
  value:
    python_version: 3.11.9
    cli_version: 0.17.4
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1720460836
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 2
      - 7
      - 16
      - 23
      - 38
      4: 3.11.9
      5: 0.17.4
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
    m:
    - 1: batch/batch_step
      6:
      - 3
